version: '2'
services:

  web:
    image: ansible/awx_web:11.2.0
    container_name: awx_web
    depends_on:
      - redis
      - memcached
      - postgres
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./awxcompose/redis_socket:/var/run/redis/:rw"
      - "./awxcompose/memcached_socket:/var/run/memcached/:rw"
    networks:
      - traefik
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    labels:
      - traefik.enable=true
      - traefik.http.routers.awx.rule=Host(`awx.example.org`)
      - traefik.http.services.awx.loadbalancer.server.port=8052
      - traefik.http.routers.awx.tls=true

  task:
    image: ansible/awx_task:11.2.0
    container_name: awx_task
    depends_on:
      - redis
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./awxcompose/redis_socket:/var/run/redis/:rw"
      - "./awxcompose/memcached_socket:/var/run/memcached/:rw"
    networks:
      - traefik
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/supervisor.conf'
      GIT_SSL_NO_VERIFY: 'true'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./awxcompose/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "./awxcompose/redis_socket:/var/run/redis/:rw"
      - "./awxcompose/memcached_socket:/var/run/memcached/:rw"
    networks:
      - traefik

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    command: ["-s", "/var/run/memcached/memcached.sock", "-a", "0666"]
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    volumes:
      - "./awxcompose/memcached_socket:/var/run/memcached/:rw"
    networks:
      - traefik

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - ./pgdocker/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 
    networks:
      - traefik

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:


networks:
  traefik:
    external: true
