version: '3'

services:
  jenkins:
    image: local/jenkins
    container_name: jenkins
    build: ./build
    volumes:
      - home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
      - GIT_SSL_NO_VERIFY=true
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.example.org`)
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
      - traefik.http.routers.jenkins.tls=true

networks:
  traefik:
    external: true

volumes:
  home:
